### ISSUE TITLE
is useSwiperContext working?

### ISSUE THREAD

**Issue by rares-lupascu** [jeongshin/react-native-awesome-swiper#16]
https://docs.react-native-awesome-swiper.site/docs/SwiperUI/ScaleSwiper/Provider

i am trying to use the context but not effects are being triggered when i interact with the slider(swipping left and right)

**Comment by rares-lupascu** [comment]
i assumed i can use are rect component as a child ... i hope am not bound to use images

**Comment by rares-lupascu** [comment]
so what i am doing is 
```
export default () => {
    return (
        <ScaleSwiper.Provider>
            <UI />
        </ScaleSwiper.Provider>
    );
};
```
inside the UI component i am using
```
const {itemCount, itemWidth, scrollX, activeIndex} = useSwiperContext();
console.log({itemCount, itemWidth, scrollX, activeIndex});
```
and down the component tree at some point i have
```
<ScaleSwiper.FlatList
                    scaleDownRate={0.3}
                    initialScrollIndex={handles.findIndex(
                        h => h.id === selectedHandle.id,
                    )}
                    data={handles}
                    renderItem={({item}) => <ProfileImage data={item} />}
                />
```

**Comment by rares-lupascu** [comment]
in the docs u have this
```
const { ref, refCallback } = useSwiperRefCallback<string>();
```
i do not need ref because we are not using the dot navigation but i do not know if not using refCallback is an issue ... not using it atm because i do no know where u export useSwiperRefCallback from

**Comment by rares-lupascu** [comment]
so i assume u renamed to the hook to useRefCallback
```
const {refCallback} = useRefCallback<FlatList<THandle>>();
console.log({itemCount, itemWidth, scrollX, activeIndex});
...
<ScaleSwiper.FlatList
                    refCallback={refCallback}
                    scrollEnabled={true}
                    scaleDownRate={0.3}
                    initialScrollIndex={handles.findIndex(
                        h => h.id === selectedHandle.id,
                    )}
                    data={handles}
                    renderItem={({item}) => <ProfileImage data={item} />}
                />
```
still nothing ... i assume the context does not get updated

**Comment by rares-lupascu** [comment]
=> components => ScaleSwiper => context => Provider.js line 9 ... change this
```
const context = useMemo(() => ({ itemCount, scrollX, itemWidth, activeIndex }), [itemCount]);
```
into this
```
const context = useMemo(() => ({ itemCount, scrollX, itemWidth, activeIndex }), [itemCount,activeIndex]);
```
the memo does not get recalculated when active index changes ... so context does not change

**Comment by jeongshin** [comment]
@rares-lupascu Thanks for reporting the issue. 🙌
I released new version. 
Please check [v0.3.3](https://github.com/jeongshin/react-native-awesome-swiper/releases/tag/v0.3.3)
Thanks for using this library and let me know if you need any other feature request!

**Comment by rares-lupascu** [comment]
will do :) good job with the package
